// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Models;

namespace WebApplication3.Migrations
{
    [DbContext(typeof(UrunlerContext))]
    [Migration("20210809150323_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication3.Models.Urunler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("fiyat")
                        .HasColumnType("int");

                    b.Property<int>("gramaj")
                        .HasColumnType("int");

                    b.Property<int>("grup_no")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("puan")
                        .HasColumnType("int");

                    b.Property<string>("urun_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("urun_no")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Urunlers");
                });
#pragma warning restore 612, 618
        }
    }
}
